name: CI - Build and Push Docker Image

on:
  push:
    branches:
      - '**'   # triggers for all branches

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      REGION: ${{ secrets.GCP_REGION }}
      PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
      REPO: python-app-repo
      IMAGE_NAME: python-app

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Configure Docker authentication
        run: gcloud auth configure-docker $REGION-docker.pkg.dev --quiet

      - name: Build Docker image
        run: |
          SHORT_SHA=$(echo "${GITHUB_SHA}" | cut -c1-7)
          IMAGE_URI="$REGION-docker.pkg.dev/$PROJECT_ID/$REPO/$IMAGE_NAME:$SHORT_SHA"
          echo "IMAGE_URI=$IMAGE_URI" >> $GITHUB_ENV
          echo "Building image: $IMAGE_URI"
          docker build -t "$IMAGE_URI" .

      - name: Push Docker image
        run: |
          echo "Pushing $IMAGE_URI"
          docker push "$IMAGE_URI"

      - name: Print image
        run: echo "Image pushed: $IMAGE_URI"

